### ISSUE TITLE
SSHFS: Tamir.SharpSsh.jsch.JSchException: Algorithm negotiation fail

### ISSUE THREAD

**Issue by bruKeba** [dokan-dev/dokan-sshfs#2]
I am using Dokan to connect to a Linux Debian system.
We have now upgraded to Debian 8.
Due to security reasons Debian 8 no longer allows a connection as root user by just entering a password, so I have to send an OpenSSH key.

By using this key I get the following exception in DokanSSHFS:

> | 2015-09-09 17:41:39 | SSHFS: Tamir.SharpSsh.jsch.JSchException: Algorithm negotiation fail
>   at Tamir.SharpSsh.jsch.Session.connect(Int32 connectTimeout)
>   at Tamir.SharpSsh.jsch.Session.connect()
>   at DokanSSHFS.SSHFS.SSHConnect()
> | 2015-09-09 17:41:39 | Error: failed to connect

Tamir.SharpSsh (version 1.1.1.13) is from 2007 and is the latest version.
Is there any update or workaround available to handle this problem?

Thanks,
Juergen

**Comment by Liryna** [comment]
~~Tamir.SharpSsh is old and should be changed, I agree with you.~~

~~https://www.nuget.org/packages/SSH.NET 
Seems to be the most used ssh nuget library.~~

~~If someone have the possibility to make the change and PR, it would be very nice !~~

Edit: See Mahxy answer

**Comment by Maxhy** [comment]
This project was updated to build and work and should be considered as a sample.
WinSSH based on dokan is originally a fork to use SSH.NET. I don't think we should do it here.

On September 10, 2015 11:32:24 AM GMT+02:00, Liryna notifications@github.com wrote:

> Tamir.SharpSsh is old and should be changed, I agree with you.
> 
> https://www.nuget.org/packages/SSH.NET
> Seems to be the most used ssh nuget library.
> 
> If someone have the possibility to make the change and PR, it would be
> very nice !
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/dokan-dev/dokan-sshfs/issues/2#issuecomment-139183392

##

**Comment by shi-yan** [comment]
I'm experiencing the same error with ubuntu. I could ssh to the ubuntu with cygwin using the same user name and password. but with sshfs, I saw this error.

I just want to test out dokan, is there a way to work around this problem? I don't have to connect to ubuntu. Mac or windows are both fine.

Thanks

**Comment by Liryna** [comment]
You can use win-sshfs:
https://github.com/dimov-cz/win-sshfs

It also use dokan.
